#!/bin/bash
# Build and install AutoAgent Status.app into ~/Applications
set -euo pipefail
cd "$(dirname "$0")"

APP_NAME="AutoAgent Status"
BUNDLE="$HOME/Applications/$APP_NAME.app"

mkdir -p build "$HOME/Applications"

# The releases repo is PUBLIC, so no token is needed — the app checks Releases
# anonymously. .update-token is optional (legacy private-repo support); leave it
# absent for a clean tokenless build.
TOKEN=$(cat .update-token 2>/dev/null || true)
B64=$(printf %s "$TOKEN" | base64)
cat > build/Token.swift <<EOF
// Generated by build.sh — do not edit.
let updateTokenB64 = "$B64"
EOF

echo "Compiling (universal: arm64 + x86_64)…"
for ARCH in arm64 x86_64; do
  swiftc -O \
    -target "$ARCH-apple-macos13.0" \
    Sources/main.swift build/Token.swift \
    -o "build/AutoAgentStatus-$ARCH" \
    -framework AppKit \
    -framework SwiftUI \
    -framework Combine \
    -framework UserNotifications \
    -framework ServiceManagement
done
lipo -create -output build/AutoAgentStatus build/AutoAgentStatus-arm64 build/AutoAgentStatus-x86_64

if [ ! -f AppIcon.icns ]; then
  echo "Generating icon…"
  swift gen-icon.swift
  iconutil -c icns AppIcon.iconset -o AppIcon.icns
fi

echo "Bundling…"
rm -rf "$BUNDLE"
mkdir -p "$BUNDLE/Contents/MacOS" "$BUNDLE/Contents/Resources"
cp Info.plist "$BUNDLE/Contents/Info.plist"
cp build/AutoAgentStatus "$BUNDLE/Contents/MacOS/AutoAgentStatus"
cp AppIcon.icns "$BUNDLE/Contents/Resources/AppIcon.icns"

echo "Signing (ad-hoc)…"
codesign --force --sign - "$BUNDLE"

echo "Done: $BUNDLE"
